server:
  bind:
    host: 0.0.0.0
    port: 80
  url: http://localhost:8081
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    - en-US
  pretty_print: true
  limit: 10
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
  level: ERROR

metadata:
  identification:
    title:
      en: pygeoapi default instance
    description:
      en: pygeoapi provides an API to geospatial data
    keywords:
      en:
        - geospatial
        - data
        - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://example.org
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Organization Name
    url: https://pygeoapi.io
  contact:
    name: Lastname, Firstname
    position: Position Title
    address: Mailing Address
    city: City
    stateorprovince: Administrative Area
    postalcode: Zip or Postal Code
    country: Country
    phone: +xx-xxx-xxx-xxxx
    fax: +xx-xxx-xxx-xxxx
    email: you@example.org
    url: Contact URL
    hours: Mo-Fr 08:00-17:00
    instructions: During hours of service. Off on weekends.
    role: pointOfContact

resources:
  bkg-grau:
    type: collection
    title: bkg-grau
    description: bk-grau via mapproxy
    keywords:
      - mapproxy
    links: []
    providers:
      - type: tile
        name: WMTSFacade
        data: http://mapproxy:80/mapproxy/service
        format:
          name: png
          mimetype: image/png
        options:
          wmts_layer: bkg
          wmts_tile_matrix_set: GLOBAL_WEBMERCATOR
          scheme: WebMercatorQuad
          metadata_format: default
          zoom:
            min: 0
            max: 20
    extents:
      spatial:
        bbox: [-180,-90,180,90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
